image: "jupyter/nbviewer"
imagePullPolicy: null

nodeSelector: null

pdbMinAvailable: 2

pdb:
  minAvailable: 1

resources:
  requests:
    memory: 256M
    cpu: "1"

annotations: {}

extraContainers: null
extraVolumes: null

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  type: LoadBalancer
  ports:
    nodePort: null

github:
  accessToken: ""
  clientId: ""
  clientSecret: ""

nbviewer:
  baseUrl: "/"
  extraArgs: []
  newrelicIni: ""

memcached:
  config:
    memoryLimit: 250
  replicaCount: 2
  # memory limits should be a bit bigger than config.memoryLimit
  resources:
    limits:
      cpu: 1
      memory: 300MB
    requests:
      cpu: 100m
      memory: 300MB
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - memcached
            topologyKey: kubernetes.io/hostname

updateStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

statuspage:
  enabled: false
  image: jupyter/nbviewer-statuspage
  resources: null
  apiKey: ""
  pageId: ""
  metricId: ""
